### ISSUE TITLE
Fails to load on Spigot 1.8.8

### ISSUE THREAD

**Issue by Lord-Cuddles** [artex-development/Lukkit#12]
**What should happen?**
Lukkit should load

**What actually happens?**
Lukkit fails to load. I have tested Lukkit 1.1.3, and it loads successfully.

**Give me the error!**
Here you go!
https://pastebin.com/LBNwdYCV

**Comment by Lord-Cuddles** [comment]
Exact spigot version is:
`[23:34:17] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[23:34:17] [Server thread/INFO]: You are 926 version(s) behind`

**Comment by mathhulk** [comment]
Guessing this was caused because of breaking API changes from the Spigot API. I'm sure there is some sort of workaround for this, but that is all up to @AL1L.

**Comment by jammehcow** [comment]
This is a direct compilation of the master branch, right?

**Comment by Lord-Cuddles** [comment]
I used the version pinned in the discord

**Comment by AL1L** [comment]
I removed reflections and now have a working version for Minecraft 1.8+.
[Lukkit-2.0-beta.jar.zip](https://github.com/artex-development/Lukkit/files/2172818/Lukkit-2.0-beta.jar.zip)
